[loader]
".vert" = "text"
".frag" = "text"
".glsl" = "text"
".png" =  "path"

[serve.static]
plugins = ["bun-plugin-tailwind"]
env = "BUN_PUBLIC_*"

[serve.static.alias]
"@acme/threeme" = "../../packages/threeme/index.ts"
"@acme/threeme/geometry" = "../../packages/threeme/src/geometry/index.ts"